/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rcorrent.view;

import br.com.rcorrent.dao.MarcaDao;
import br.com.rcorrent.dao.ModeloDao;
import br.com.rcorrent.dao.VeiculoDao;
import br.com.rcorrent.enuns.Estados;
import br.com.rcorrent.model.Marca;
import br.com.rcorrent.model.Modelo;
import br.com.rcorrent.model.Veiculo;
import br.com.rcorrent.tools.ComboBoxUtils;
import br.com.rcorrent.tools.JTableUtils;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author rcorrent
 */
public class VeiculoView extends javax.swing.JDialog {
    
    private Integer estado;
    
    private final MarcaDao marcaDao = new MarcaDao();
    private final ModeloDao modeloDao = new ModeloDao();
    private final VeiculoDao veiculoDao = new VeiculoDao();
    
    private Modelo modelo;
    private Marca marca;
    private Veiculo veiculo;

    public VeiculoView(Dialog owner, boolean modal) {
        super(owner, modal);
        
        initComponents();
        
        //deixar o campo valor inicial desabilitado
        jtfValor.setEnabled(false);
        
        this.estado = Estados.getPadrao().getEstado();
        
        //desabilitar botões
        estadoInicialDosBotoes();
        
        //desabilitar os campos
        habilitarCampos(false);
        
        //preencher e formatar os campo da tabela de consulta
        preencherTabelaVeiculos();
        JTableUtils.formatarJtable(jtListaVeiculo,new int[]{100,90,50,40,40,40,40});
        
        //preencher JComboBox de MARCA e MODELO
        ComboBoxUtils.preencherCombo(jcbMarca, marcaDao.getAllMarca());
        ComboBoxUtils.preencherCombo(jcbModelo, modeloDao.getAllModelo());
        
        //deixar jcbModelo desabilitada
        jcbModelo.setEnabled(false);
        jcbMarca.setEnabled(false);
    }
    
    
    
    /**
     * Creates new form VeiculoView
     */
    public VeiculoView() {
        initComponents();
        
        //deixar o campo valor inicial desabilitado
        jtfValor.setEnabled(false);
        
        this.estado = Estados.getPadrao().getEstado();
        
        //desabilitar botões
        estadoInicialDosBotoes();
        
        //desabilitar os campos
        habilitarCampos(false);
        //preencher e formatar os campo da tabela de consulta
        preencherTabelaVeiculos();
        JTableUtils.formatarJtable(jtListaVeiculo,new int[]{100,90,50,40,40,40,40});
        
        //preencher JComboBox de MARCA e MODELO
        ComboBoxUtils.preencherCombo(jcbMarca, marcaDao.getAllMarca());
        ComboBoxUtils.preencherCombo(jcbModelo, modeloDao.getAllModelo());
        
        //deixar jcbModelo desabilitada
        jcbModelo.setEnabled(false);
        jcbMarca.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jpBotoes = new javax.swing.JPanel();
        jbNovo = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbGravar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcbMarca = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcbModelo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jftfPlaca = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jftfChassi = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jftfRenavan = new javax.swing.JFormattedTextField();
        jftfAnoModelo = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jftfAnoFabricacao = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jftfCapacidade = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jftfEixo = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jftfAutonomia = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jftfConsumo = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jcbFiltrar = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jtfValor = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaVeiculo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpBotoes.setBackground(new java.awt.Color(222, 222, 222));

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rcorrent/icons/1491671388_new10.png"))); // NOI18N
        jbNovo.setMnemonic('N');
        jbNovo.setText("Novo");
        jbNovo.setIconTextGap(10);
        jbNovo.setPreferredSize(new java.awt.Dimension(110, 27));
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });
        jpBotoes.add(jbNovo);

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rcorrent/icons/1491671388_new10.png"))); // NOI18N
        jbAlterar.setMnemonic('A');
        jbAlterar.setText("Alterar");
        jbAlterar.setIconTextGap(10);
        jbAlterar.setPreferredSize(new java.awt.Dimension(110, 27));
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });
        jpBotoes.add(jbAlterar);

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rcorrent/icons/1491672387_garbage.png"))); // NOI18N
        jbExcluir.setMnemonic('E');
        jbExcluir.setText("Excluir");
        jbExcluir.setIconTextGap(10);
        jbExcluir.setPreferredSize(new java.awt.Dimension(110, 27));
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });
        jpBotoes.add(jbExcluir);

        jbGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rcorrent/icons/1491672401_vintage11.png"))); // NOI18N
        jbGravar.setMnemonic('G');
        jbGravar.setText("Gravar");
        jbGravar.setIconTextGap(10);
        jbGravar.setPreferredSize(new java.awt.Dimension(110, 27));
        jbGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarActionPerformed(evt);
            }
        });
        jpBotoes.add(jbGravar);

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rcorrent/icons/1491672468_cancel-2.png"))); // NOI18N
        jbCancelar.setMnemonic('C');
        jbCancelar.setText("Cancelar");
        jbCancelar.setIconTextGap(10);
        jbCancelar.setPreferredSize(new java.awt.Dimension(110, 27));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jpBotoes.add(jbCancelar);

        jLabel1.setText("Marca");

        jcbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMarcaActionPerformed(evt);
            }
        });

        jLabel2.setText("Modelo");

        jLabel3.setText("Placa");

        try {
            jftfPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Chassi");

        try {
            jftfChassi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#UU###UU0#U######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Renavan");

        jLabel6.setText("Ano Modelo");

        try {
            jftfRenavan.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftfAnoModelo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("Ano Fabricação");

        try {
            jftfAnoFabricacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setText("Capacidade de Carga (Ton)");

        try {
            jftfCapacidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##TON")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("Quantidade EIXO");

        try {
            jftfEixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("Autonomia");

        try {
            jftfAutonomia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###Km")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setText("Consumo");

        try {
            jftfConsumo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.#Km/lt")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jcbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(322, 322, 322))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jftfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftfChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jftfRenavan)
                                .addGap(322, 322, 322))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jftfCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jftfAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jftfAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jftfEixo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jftfAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jftfConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfRenavan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jftfAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftfAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftfEixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftfAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jftfConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftfCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jTabbedPane1.addTab("Cadastrar", jPanel1);

        jLabel12.setText("Filtro");

        jcbFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "Marca", "Modelo", "Placa", "Ano", "Eixo" }));
        jcbFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFiltrarActionPerformed(evt);
            }
        });

        jLabel13.setText("Valor");

        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rcorrent/icons/1491673267_search.png"))); // NOI18N
        jbPesquisar.setMnemonic('P');
        jbPesquisar.setText("Pesquisar");
        jbPesquisar.setIconTextGap(10);
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jtListaVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Placa", "Fabricação", "Modelo", "Eixos", "Capacidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListaVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListaVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListaVeiculo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(145, 145, 145)
                                .addComponent(jLabel13))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jcbFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbPesquisar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consultar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setSize(new java.awt.Dimension(844, 451));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        estadoDosBotoesAoInserirNovo();
        habilitarCampos(true);
        limparCampo();
        this.estado = Estados.getInsercao().getEstado();
        //preencher JComboBox de MARCA e MODELO
        ComboBoxUtils.preencherCombo(jcbMarca, marcaDao.getAllMarca());
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        estadoBotoesModoEdicao();
        habilitarCampos(true);
        this.estado = Estados.getAlteracao().getEstado();
        //preencher JComboBox de MARCA e MODELO
        ComboBoxUtils.preencherCombo(jcbMarca, marcaDao.getAllMarca());
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        try {
            Veiculo veiculoDeletar = getVeiculo();
            //tratar (se o VEICULO veio com todos os campos corretos ou se ela veio por completo.
                if (veiculoDeletar == null) {
                    JOptionPane.showMessageDialog(null, "Selecione um Veiculo para excluir");
                    return;
                }
                //criando uma optionPane para confirmar a exclusão
                if (JOptionPane.showConfirmDialog(null, "Deseja Realment exlcuir o Veículo?", "ATENÇÃO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    veiculoDao.excluirVeiculo(veiculoDeletar);
                    JOptionPane.showMessageDialog(null, "Veículo excluído com sucesso!!!");
                    limparCampo();
                    habilitarCampos(false);
                    //desabilitar botões
                    estadoInicialDosBotoes();
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao excluir Veículo");
            } finally {
                veiculoDao.fecharCursores();
                limparCampo();
                preencherTabelaVeiculos();
            }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGravarActionPerformed
        try {
            Veiculo veiculoGravar = getVeiculo();
            //testa se o VEICULO veio completa, com todos os itens a serem salvos
            if(veiculoGravar == null){
                return;
            }
            //testa se está ocorrendo uma gravação
            if(this.estado == Estados.getInsercao().getEstado()){
                veiculoDao.inserirVeiculo(veiculoGravar);
                JOptionPane.showMessageDialog(null, "Veículo cadastrado com sucesso!");
            }
            //testa se está ocorrendo um update ou uma alteração
            if(this.estado == Estados.getAlteracao().getEstado()){
                veiculoDao.alterarVeiculo(veiculoGravar);
                JOptionPane.showMessageDialog(null, "Registro de Veículo alterado com sucesso!");
            }

            //deixar os botões em estado PADRAO
            estadoPadraoDosBotoes();

            //desabilitar os campos
            habilitarCampos(false);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao salvar Veículo..");
        } finally {
            veiculoDao.fecharCursores();
            limparCampo();
            preencherTabelaVeiculos();
        }
    }//GEN-LAST:event_jbGravarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        //definir estado padrão inicial aos botoes
        estadoInicialDosBotoes();

        //PERGUNTAR SOBRE ENUM
        this.estado = Estados.getPadrao().getEstado();

        limparCampo();

        habilitarCampos(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtListaVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListaVeiculoMouseClicked
        try {
            if(evt.getClickCount() > 1){
                Veiculo veiculo = veiculoDao.getByPlacaVeiculo(jtListaVeiculo.getValueAt(jtListaVeiculo.getSelectedRow(), 2).toString());
                setVeiculo(veiculo);
                jTabbedPane1.setSelectedIndex(0);
                estadoBotoesModoEdicao();
                jbGravar.setEnabled(false);
                jcbModelo.setEnabled(false);
                jcbMarca.setEnabled(false);
            }
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jtListaVeiculoMouseClicked

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        List<String> campos = new ArrayList<>();
        campos.add("NM_MARCA");
        campos.add("NM_MODELO");
        campos.add("NR_PLACA");
        campos.add("NR_ANO_FABRICACAO");
        campos.add("NR_ANO_MODELO");
        campos.add("QD_EIXO");
        campos.add("VL_CAPACIDADE_TON");
        
        switch(jcbFiltrar.getSelectedIndex()){
            case 0:{//caso seja escolhido a opção GERAL
                preencherTabelaVeiculos();
            } break;
            case 1:{//caso seja escolhido a opção MARCA
                //testar para valores numéricos
                try {
                    JTableUtils.preencherJTable(jtListaVeiculo, veiculoDao.resultSetgetByMarcaVeiculo(jtfValor.getText()), campos);                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }break;
            case 2:{//caso seja escolhido a opção MODELO
                try {
                    JTableUtils.preencherJTable(jtListaVeiculo, veiculoDao.resultSetgetByModeloVeiculo(jtfValor.getText()), campos);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }break;
            case 3:{//caso seja escolhido a opção PLACA
                try {
                    JTableUtils.preencherJTable(jtListaVeiculo, veiculoDao.resultSetgetByPlacaVeiculo(jtfValor.getText()), campos);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }break;
            case 4:{//caso seja escolhido a opção ANO
                try {
                    JTableUtils.preencherJTable(jtListaVeiculo, veiculoDao.resultSetgetByAnoVeiculo(Integer.parseInt(jtfValor.getText())), campos);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }break;
            case 5:{//caso seja escolhido a opção EIXO
                try {
                    JTableUtils.preencherJTable(jtListaVeiculo, veiculoDao.resultSetgetByEixoVeiculo(Integer.parseInt(jtfValor.getText())), campos);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }break;
        }
        
        veiculoDao.fecharCursores();
        
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jcbFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFiltrarActionPerformed
       if(jcbFiltrar.getSelectedIndex() == 0){
            jtfValor.setEnabled(false);
            jtfValor.setText("");
        }else{
            jtfValor.setEnabled(true);
            jtfValor.setText("");
        }
    }//GEN-LAST:event_jcbFiltrarActionPerformed

    private void jcbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMarcaActionPerformed
        try {
            if(jcbMarca.getSelectedItem() != null){
                Marca marcaSelect = (Marca) jcbMarca.getSelectedItem();
                ComboBoxUtils.preencherCombo(jcbModelo, modeloDao.getModelosByIdMarca(marcaSelect.getCodigoMarca().longValue()));
                jcbModelo.setEnabled(true);                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jcbMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeiculoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbGravar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JComboBox<String> jcbFiltrar;
    private javax.swing.JComboBox<String> jcbMarca;
    private javax.swing.JComboBox<String> jcbModelo;
    private javax.swing.JFormattedTextField jftfAnoFabricacao;
    private javax.swing.JFormattedTextField jftfAnoModelo;
    private javax.swing.JFormattedTextField jftfAutonomia;
    private javax.swing.JFormattedTextField jftfCapacidade;
    private javax.swing.JFormattedTextField jftfChassi;
    private javax.swing.JFormattedTextField jftfConsumo;
    private javax.swing.JFormattedTextField jftfEixo;
    private javax.swing.JFormattedTextField jftfPlaca;
    private javax.swing.JFormattedTextField jftfRenavan;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JTable jtListaVeiculo;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
    /**PREENCHER TABELA DE VEICULOS.
     * 
     */
    public void preencherTabelaVeiculos(){
        List<String> campos = new ArrayList<>();
        campos.add("NM_MARCA");
        campos.add("NM_MODELO");
        campos.add("NR_PLACA");
        campos.add("NR_ANO_FABRICACAO");
        campos.add("NR_ANO_MODELO");
        campos.add("QD_EIXO");
        campos.add("VL_CAPACIDADE_TON");
        
        JTableUtils.preencherJTable(jtListaVeiculo, veiculoDao.resultSetGetAllVeiculo(0.0), campos);
    }
    
    
    /**SET VEICULO.
     * Ao ser 'chamada', ela carrega NA JFORM as informações de uma marca
     */
    public void setVeiculo(Veiculo veiculo){
        try {
            System.out.println("modelo " + veiculo.getModelo().getNomeModelo());
            System.out.println("marca " + veiculo.getModelo().getMarca().getNomeMarca());
            
            jcbModelo.setSelectedItem(veiculo.getModelo());
            jcbMarca.setSelectedItem(veiculo.getModelo().getMarca());
            
            jftfPlaca.setText(veiculo.getNumeroPlaca().toUpperCase());
            jftfChassi.setText(veiculo.getNumeroChassi());
            jftfRenavan.setText(veiculo.getNumeroRenavan());
            jftfAnoModelo.setText(veiculo.getAnoModelo().toString());
            jftfAnoFabricacao.setText(veiculo.getAnoFabricacao().toString());
            jftfCapacidade.setText(veiculo.getCapacidadeEmTonelada().toString());
            jftfEixo.setText(veiculo.getQuantidadeDeEixo().toString());
            jftfAutonomia.setText(veiculo.getAutonomia().toString());
            jftfConsumo.setText(veiculo.getConsumoPorKm().toString());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**VALIDAR CAMPOS.
     * Método que faz a validação dos campos
     * se todos estiverem preenchidos, OK
     */
    public Boolean validarVeiculo(){
        try {
            if(jftfPlaca.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Informe uma Placa");
                jftfPlaca.grabFocus();
                return false;
            }
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    /**GET VEICULO.
     * Método para carregar uma MARCA
     * com informações da JForm completada
     * @return 
     */
    public Veiculo getVeiculo(){
        try {
            modelo = new Modelo();
            veiculo = new Veiculo();
            
            modelo = (Modelo) jcbModelo.getSelectedItem();
            
            if(!validarVeiculo()){
                return null;
            } else {
                veiculo.setModelo(modelo);
                veiculo.setNumeroPlaca(jftfPlaca.getText());
                veiculo.setNumeroChassi(jftfChassi.getText());
                veiculo.setNumeroRenavan(jftfRenavan.getText());
                veiculo.setAnoModelo(Integer.parseInt(jftfAnoModelo.getText()));
                veiculo.setAnoFabricacao(Integer.parseInt(jftfAnoFabricacao.getText()));
                veiculo.setCapacidadeEmTonelada(Double.parseDouble(jftfCapacidade.getText().replace("TON", "")));
                veiculo.setQuantidadeDeEixo(Integer.parseInt(jftfEixo.getText()));
                veiculo.setAutonomia(Double.parseDouble(jftfAutonomia.getText().replace("Km", "")));
                veiculo.setConsumoPorKm(Double.parseDouble(jftfConsumo.getText().replace("Km/lt", "")));
                
                return veiculo;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    /**Habilita/Desabilita campos.
     * Método que ao iniciar, habilita ou desabilita os campos
     */
    public void habilitarCampos(boolean estado){
        jftfPlaca.setEnabled(estado);
        jftfChassi.setEnabled(estado);
        jftfRenavan.setEnabled(estado);
        jftfAnoModelo.setEnabled(estado);
        jftfAnoFabricacao.setEnabled(estado);
        jftfCapacidade.setEnabled(estado);
        jftfEixo.setEnabled(estado);
        jftfAutonomia.setEnabled(estado);
        jftfConsumo.setEnabled(estado);
        
        jcbModelo.setEnabled(estado);
        jcbMarca.setEnabled(estado);

    }
    
    /**LimparCampos
     * Método para limpar caixas de JTextField no JForm
     */
    public void limparCampo(){
        jftfPlaca.setText("");
        jftfChassi.setText("");
        jftfRenavan.setText("");
        jftfAnoModelo.setText("");
        jftfAnoFabricacao.setText("");
        jftfCapacidade.setText("");
        jftfEixo.setText("");
        jftfAutonomia.setText("");
        jftfConsumo.setText("");
    } 
    
    /**Método para habilitar/desabilitar os BOTÓES, ao iniciar a tela.
     * Ao iniciar, manter os botões principais em estado de habilitado
     */
    public void estadoPadraoDosBotoes(){
        jbNovo.setEnabled(true);
        jbAlterar.setEnabled(true);
        jbExcluir.setEnabled(true);
        
        jbGravar.setEnabled(false);
        jbCancelar.setEnabled(false);
    }
    
    /**Métod para habilitar/desabilitar os BOTÕES, quando se está em modo de edição.
     * 
     */
    public void estadoBotoesModoEdicao(){
        jbNovo.setEnabled(false);
        jbAlterar.setEnabled(true);
        jbExcluir.setEnabled(true);
        
        jbGravar.setEnabled(true);
        jbCancelar.setEnabled(true);
    }
    /**Métod para habilitar/desabilitar os BOTÕES, quando se está adicionando novo.
     * 
     */
    public void estadoDosBotoesAoInserirNovo(){
        jbNovo.setEnabled(false);
        jbAlterar.setEnabled(false);
        jbExcluir.setEnabled(false);
        
        jbGravar.setEnabled(true);
        jbCancelar.setEnabled(true);
    }
    
    /**Método inicial dos botões
     * 
     */
    public void estadoInicialDosBotoes(){
        jbNovo.setEnabled(true);
        jbAlterar.setEnabled(false);
        jbExcluir.setEnabled(false);
        
        jbGravar.setEnabled(false);
        jbCancelar.setEnabled(false);
    }
}
