/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rcorrent.view.busca;

import br.com.rcorrent.dao.VeiculoDao;
import br.com.rcorrent.tools.JTableUtils;
import br.com.rcorrent.view.VeiculoView;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author rcorrent
 */
public class BuscarVeiculo extends javax.swing.JDialog {
    
    private final VeiculoDao veiculoDao = new VeiculoDao();
    private Double peso = 0.0;
    public String placaVeiculo;

    public BuscarVeiculo(Dialog owner, boolean modal) {
        super(owner, modal);
        initComponents();
        jtfValor.setEnabled(false);
        JTableUtils.formatarJtable(jtListaVeiculo,new int[]{100,90,50,40,40,40,40});
    }
    public BuscarVeiculo(Dialog owner, boolean modal, Double peso) {
        super(owner, modal);
        initComponents();
        jtfValor.setEnabled(false);
        JTableUtils.formatarJtable(jtListaVeiculo,new int[]{100,90,50,40,40,40,40});
        this.peso = peso;
    }
    
    
    
    /**
     * Creates new form BuscarVeiculo
     */
    public BuscarVeiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jtfValor.setEnabled(false);
        JTableUtils.formatarJtable(jtListaVeiculo,new int[]{100,90,50,40,40,40,40});
    }
    public BuscarVeiculo(java.awt.Frame parent, boolean modal, Double peso) {
        super(parent, modal);
        initComponents();
        jtfValor.setEnabled(false);
        JTableUtils.formatarJtable(jtListaVeiculo,new int[]{100,90,50,40,40,40,40});
        this.peso = peso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jcbFiltrar = new javax.swing.JComboBox<>();
        jtfValor = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaVeiculo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel12.setText("Filtro");

        jcbFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "Marca", "Modelo", "Placa", "Ano", "Eixo" }));
        jcbFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFiltrarActionPerformed(evt);
            }
        });

        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rcorrent/icons/1491673267_search.png"))); // NOI18N
        jbPesquisar.setMnemonic('P');
        jbPesquisar.setText("Pesquisar");
        jbPesquisar.setIconTextGap(10);
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jLabel13.setText("Valor");

        jtListaVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Placa", "Fabricação", "Modelo", "Eixos", "Capacidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListaVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListaVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListaVeiculo);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rcorrent/icons/1491671388_new10.png"))); // NOI18N
        jButton1.setText("Adicionar Novo");
        jButton1.setIconTextGap(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfValor)
                        .addGap(18, 18, 18)
                        .addComponent(jbPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(887, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFiltrarActionPerformed
        if(jcbFiltrar.getSelectedIndex() == 0){
            jtfValor.setEnabled(false);
        }else{
            jtfValor.setEnabled(true);
        }
    }//GEN-LAST:event_jcbFiltrarActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        List<String> campos = new ArrayList<>();
        campos.add("NM_MARCA");
        campos.add("NM_MODELO");
        campos.add("NR_PLACA");
        campos.add("NR_ANO_FABRICACAO");
        campos.add("NR_ANO_MODELO");
        campos.add("QD_EIXO");
        campos.add("VL_CAPACIDADE_TON");

        switch(jcbFiltrar.getSelectedIndex()){
            case 0:{//caso seja escolhido a opção GERAL
                preencherTabelaVeiculos();
            } break;
            case 1:{//caso seja escolhido a opção MARCA
                //testar para valores numéricos
                try {
                    JTableUtils.preencherJTable(jtListaVeiculo, veiculoDao.resultSetgetByMarcaVeiculo(jtfValor.getText()), campos);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }break;
            case 2:{//caso seja escolhido a opção MODELO
                try {
                    JTableUtils.preencherJTable(jtListaVeiculo, veiculoDao.resultSetgetByModeloVeiculo(jtfValor.getText()), campos);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }break;
            case 3:{//caso seja escolhido a opção PLACA
                try {
                    JTableUtils.preencherJTable(jtListaVeiculo, veiculoDao.resultSetgetByPlacaVeiculo(jtfValor.getText()), campos);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }break;
            case 4:{//caso seja escolhido a opção ANO
                try {
                    JTableUtils.preencherJTable(jtListaVeiculo, veiculoDao.resultSetgetByAnoVeiculo(Integer.parseInt(jtfValor.getText())), campos);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }break;
            case 5:{//caso seja escolhido a opção EIXO
                try {
                    JTableUtils.preencherJTable(jtListaVeiculo, veiculoDao.resultSetgetByEixoVeiculo(Integer.parseInt(jtfValor.getText())), campos);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }break;
        }

        veiculoDao.fecharCursores();

    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jtListaVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListaVeiculoMouseClicked
        try {
            if(evt.getClickCount() > 1){
                this.placaVeiculo = jtListaVeiculo.getValueAt(jtListaVeiculo.getSelectedRow(), 2).toString();                
                dispose();
            }
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jtListaVeiculoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VeiculoView veiculoView = new VeiculoView(this, true);
        veiculoView.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarVeiculo dialog = new BuscarVeiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JComboBox<String> jcbFiltrar;
    private javax.swing.JTable jtListaVeiculo;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
    /**PREENCHER TABELA DE VEICULOS.
     * 
     */
    public void preencherTabelaVeiculos(){
        List<String> campos = new ArrayList<>();
        campos.add("NM_MARCA");
        campos.add("NM_MODELO");
        campos.add("NR_PLACA");
        campos.add("NR_ANO_FABRICACAO");
        campos.add("NR_ANO_MODELO");
        campos.add("QD_EIXO");
        campos.add("VL_CAPACIDADE_TON");
        
        JTableUtils.preencherJTable(jtListaVeiculo, veiculoDao.resultSetGetAllVeiculo(this.peso), campos);
    }


}
